### ISSUE TITLE
How to customize an env

### ISSUE THREAD

**Issue by GuanqiHe** [huggingbutt/huggingbutt#15]
Is there any doc or example that I can customize my own env? Hope to get a protocol or an example

**Comment by 3D-Wizard** [comment]
I will be updating the README.md with instructions or a example for custom environments over the next few days.

**Comment by 3D-Wizard** [comment]
> Is there any doc or example that I can customize my own env? Hope to get a protocol or an example

I will be updating README.md with instructions or an example for custom env over the next few days.

**Comment by huggingbutt** [comment]
By following the guidance provided in README.md, you will be able to create your environment.
